In [1]:
import pandas as pd
import numpy as np
import sys
sys.path.append('../../../../def')

In [2]:
import str_process

In [25]:
authors_cp_name = pd.read_excel('./excel/作者关系2.0.xlsx')

In [4]:
authors_cp_id = pd.read_excel('./excel/作者编号配对2.0.xlsx')

In [26]:
for i in range (len(authors_cp_name)):
    for j in range(2):
        authors_cp_name.iloc[i,j]=str_process.chinese_all(authors_cp_name.iloc[i,j])

In [27]:
authors_cp_plus = authors_cp_name

In [28]:
authors_cp_plus.insert(loc=2,column='result',value=(''))

In [29]:
authors_cp_plus

      author_a author_b result organization
0         True     True            中国科学技术大学
1         True     True            中国科学技术大学
2         True     True            中国科学技术大学
3         True     True            中国科学技术大学
4         True     True            中国科学技术大学
5         True     True                福州大学
6         True     True                福州大学
7         True     True                福州大学
8         True     True                福州大学
9         True     True              西安交通大学
10        True     True              西安交通大学
11        True     True              西安交通大学
12        True     True              西安交通大学
13        True     True              沈阳化工大学
14        True     True              沈阳化工大学
15        True     True              沈阳化工大学
16        True     True                暨南大学
17        True     True                天津大学
18        True     True                天津大学
19        True     True                天津大学
20        True     True                天津大学
21        True     True                天津大学
22        True     True                天津大学
23        True     True                武汉大学
24        True    False              西南交通大学
25       False    False              西南交通大学
26       False    False              西南交通大学
27        True    False              西南交通大学
28       False    False              西南交通大学
29       False    False              西南交通大学
...        ...      ...    ...          ...
12556    False    False                临沂大学
12557    False    False                临沂大学
12558    False    False                临沂大学
12559    False    False                临沂大学
12560    False    False                临沂大学
12561    False    False              沈阳化工大学
12562    False    False              沈阳化工大学
12563    False    False              江苏科技大学
12564    False    False                山东大学
12565    False    False                山东大学
12566    False    False                浙江大学
12567    False    False                浙江大学
12568    False    False              湖北师范学院
12569    False    False              湖北师范学院
12570    False    False              湖北师范学院
12571    False    False                渤海大学
12572    False    False             哈尔滨工业大学
12573    False    False             哈尔滨工业大学
12574    False    False             哈尔滨工业大学
12575    False     True              北京交通大学
12576    False     True              北京交通大学
12577    False     True              北京交通大学
12578     True     True              北京交通大学
12579    False     True              北京交通大学
12580    False    False              华中科技大学
12581    False    False                中南大学
12582    False    False                中南大学
12583    False     True                汕头大学
12584     True     True                汕头大学
12585    False    False              安徽工业大学

[12586 rows x 4 columns]

In [32]:
authors_cp_plus['resule']=authors_cp_plus['author_a']*authors_cp_plus['author_b']

In [33]:
authors_cp_plus

      author_a author_b result organization resule
0         True     True            中国科学技术大学      1
1         True     True            中国科学技术大学      1
2         True     True            中国科学技术大学      1
3         True     True            中国科学技术大学      1
4         True     True            中国科学技术大学      1
5         True     True                福州大学      1
6         True     True                福州大学      1
7         True     True                福州大学      1
8         True     True                福州大学      1
9         True     True              西安交通大学      1
10        True     True              西安交通大学      1
11        True     True              西安交通大学      1
12        True     True              西安交通大学      1
13        True     True              沈阳化工大学      1
14        True     True              沈阳化工大学      1
15        True     True              沈阳化工大学      1
16        True     True                暨南大学      1
17        True     True                天津大学      1
18        True     True                天津大学      1
19        True     True                天津大学      1
20        True     True                天津大学      1
21        True     True                天津大学      1
22        True     True                天津大学      1
23        True     True                武汉大学      1
24        True    False              西南交通大学      0
25       False    False              西南交通大学      0
26       False    False              西南交通大学      0
27        True    False              西南交通大学      0
28       False    False              西南交通大学      0
29       False    False              西南交通大学      0
...        ...      ...    ...          ...    ...
12556    False    False                临沂大学      0
12557    False    False                临沂大学      0
12558    False    False                临沂大学      0
12559    False    False                临沂大学      0
12560    False    False                临沂大学      0
12561    False    False              沈阳化工大学      0
12562    False    False              沈阳化工大学      0
12563    False    False              江苏科技大学      0
12564    False    False                山东大学      0
12565    False    False                山东大学      0
12566    False    False                浙江大学      0
12567    False    False                浙江大学      0
12568    False    False              湖北师范学院      0
12569    False    False              湖北师范学院      0
12570    False    False              湖北师范学院      0
12571    False    False                渤海大学      0
12572    False    False             哈尔滨工业大学      0
12573    False    False             哈尔滨工业大学      0
12574    False    False             哈尔滨工业大学      0
12575    False     True              北京交通大学      0
12576    False     True              北京交通大学      0
12577    False     True              北京交通大学      0
12578     True     True              北京交通大学      1
12579    False     True              北京交通大学      0
12580    False    False              华中科技大学      0
12581    False    False                中南大学      0
12582    False    False                中南大学      0
12583    False     True                汕头大学      0
12584     True     True                汕头大学      1
12585    False    False              安徽工业大学      0

[12586 rows x 5 columns]

In [35]:
list = authors_cp_plus['resule']==1

In [37]:
authors_cp_plus.loc[list]

      author_a author_b result     organization resule
0         True     True                中国科学技术大学      1
1         True     True                中国科学技术大学      1
2         True     True                中国科学技术大学      1
3         True     True                中国科学技术大学      1
4         True     True                中国科学技术大学      1
5         True     True                    福州大学      1
6         True     True                    福州大学      1
7         True     True                    福州大学      1
8         True     True                    福州大学      1
9         True     True                  西安交通大学      1
10        True     True                  西安交通大学      1
11        True     True                  西安交通大学      1
12        True     True                  西安交通大学      1
13        True     True                  沈阳化工大学      1
14        True     True                  沈阳化工大学      1
15        True     True                  沈阳化工大学      1
16        True     True                    暨南大学      1
17        True     True                    天津大学      1
18        True     True                    天津大学      1
19        True     True                    天津大学      1
20        True     True                    天津大学      1
21        True     True                    天津大学      1
22        True     True                    天津大学      1
23        True     True                    武汉大学      1
31        True     True                    浙江大学      1
32        True     True                    浙江大学      1
33        True     True                  兰州理工大学      1
34        True     True                  兰州理工大学      1
35        True     True                  兰州理工大学      1
36        True     True                  浙江工业大学      1
...        ...      ...    ...              ...    ...
4348      True     True                  河南理工大学      1
4349      True     True                  河南理工大学      1
4350      True     True                  河南理工大学      1
4351      True     True                  河南理工大学      1
4352      True     True                  中国矿业大学      1
4353      True     True                  中国矿业大学      1
4354      True     True                  中国矿业大学      1
4355      True     True                  北方工业大学      1
4356      True     True                  北方工业大学      1
4357      True     True                  浙江工业大学      1
4358      True     True                  浙江工业大学      1
4359      True     True                  江苏师范大学      1
4360      True     True                  江苏师范大学      1
4361      True     True                  江苏师范大学      1
4363      True     True          中国人民解放军火箭军工程大学      1
4364      True     True          中国人民解放军火箭军工程大学      1
4365      True     True          中国人民解放军火箭军工程大学      1
4366      True     True          中国人民解放军火箭军工程大学      1
4369      True     True                  北京科技大学      1
4370      True     True                  北京科技大学      1
4371      True     True                  曲阜师范大学      1
4372      True     True         中国人民解放军第二炮兵工程大学      1
4373      True     True         中国人民解放军第二炮兵工程大学      1
4374      True     True                北京信息科技大学      1
4375      True     True                北京信息科技大学      1
10588     True     True                  湖南城市学院      1
10590     True     True                  湖南城市学院      1
12156     True     True                  湖南城市学院      1
12578     True     True                  北京交通大学      1
12584     True     True                    汕头大学      1

[4197 rows x 5 columns]

In [38]:
authors_cp_chinese = pd.read_excel('./excel/作者关系2.0.xlsx')

In [41]:
authors_cp_chinese_list=authors_cp_chinese.loc[list]

In [42]:
authors_cp_id_list=authors_cp_id.loc[list]

In [47]:
authors_cp_chinese_list.reset_index(inplace=True)

In [48]:
authors_cp_id_list.reset_index(inplace=True)

In [52]:
authors_cp_chinese_list.drop('index',axis=1,inplace=True)

/home/baizhen/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [54]:
authors_cp_id_list.drop('index',axis=1,inplace=True)

/home/baizhen/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [59]:
authors_cp_id_list.to_excel('./excel/作者关系全中文关系-编号版.xlsx')

In [60]:
authors_cp_chinese_list.to_excel('./excel/作者关系全中文关系-姓名版.xlsx')